import os
import os.path
from datetime import datetime

DIR = '.'
folders = [os.path.join(DIR, o) for o in os.listdir(DIR) 
                    if os.path.isdir(os.path.join(DIR, o))]

questions = []

def process(folder):
    #print("Processing %s " % folder)
    s = folder[2:].split('.')
    title = s[1].strip()
    id = s[0]
    files = [os.path.join(folder, o) for o in os.listdir(folder) 
                    if os.path.isfile(os.path.join(folder, o))]
    blog = ""
    leetcode = ""
    diff = ""
    type = "Algorithm"
    tags = set()
    langs = set()
    for f in files:
        extension = os.path.splitext(f)[1]
        langs.add(extension)
        file = open(f, "r")
        lineNum = 1
        if "sql" in f:
            type = "Database"
        for line in file:
            if "helloacm" in line:
                blog = line.split(' ')[1]
            elif "leetcode" in line:
                leetcode = line.split(' ')[1]
            elif "MEDIUM" in line or "EASY" in line or "HARD" in line:
                s = line.split(',')
                for x in s[1:]:
                    tags.add(x.strip())
                diff = s[0].split(' ')[1]
            lineNum += 1
            if lineNum > 5:
                break
        file.close()
    return { "blog": blog.strip(), 
        "diff": diff,
        "id": id,
        "title": title,
        "tags": list(tags),
        "leetcode": leetcode.strip(),
        "type": type,
        "langs": list(langs),
        "count": str(len(files)),
        "github": "https://github.com/DoctorLai/ACM/tree/master/leetcode/" + id + ".%20" + title.replace(" ", "%20")
    }

for x in folders:
    questions.append(process(x))

print("""
# Algorithms
| ID | Blog | Solutions | Diffculty | Tags |
|:----:|:----:|:-------:|:----:|:----:|
""")

Algorithm = 0
for x in questions:
    if x['type'] == "Algorithm":
        Algorithm += 1
        print("| [" + x['id'] + "](" + x['leetcode'] + ") | [" + x['title'] + "](" + x['blog'] + ") | [" + x['count'] + "](" + x['github'] + ")<br/>" + "<BR/>".join(x['langs']) + " | " + x['diff'] + " | " + "<BR/>".join(x['tags']) + " |")

print("""
# Database
| ID | Blog | Solutions | Diffculty | Tags |
|:----:|:----:|:-------:|:----:|:----:|
""")

Database = 0
for x in questions:
    if x['type'] == "Database":
        Database += 1
        print("| [" + x['id'] + "](" + x['leetcode'] + ") | [" + x['title'] + "](" + x['blog'] + ") | [" + x['count'] + "](" + x['github'] + ")<br/>" + "<BR/>".join(x['langs']) + " | " + x['diff'] + " | " + "<BR/>".join(x['tags']) + " |")

print("Total *" + str(Algorithm + Database) + "* Questions: *" + str(Database) + "* Database, *" + str(Algorithm) + "* Algorithms")

now = datetime.now()
print("*Index generated by [script](https://github.com/DoctorLai/ACM/blob/master/leetcode/list.py)* at " + now.strftime("%d/%m/%Y %H:%M:%S"))

